### PR TITLE
feat: create workflow to lighthouse

### PR DESCRIPTION
**Pull request by jonataspinto**
## Description

Validação com dados do Lighthouse no workflow para build/deploy na AWS.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

### CODE REVIEW

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by estartandodevs** [comment]
[Criação de rotina para Lighthouse](https://trello.com/c/xGVZp4yL/10-cria%C3%A7%C3%A3o-de-rotina-para-lighthouse)

**Comment by jonataspinto** [comment]
Aí galera! Muito top!

@alanaraujop @yagovaluchedevs @ramonxm @Brenont @joaoprferreira

**Comment by ramonxm** [comment]
> Aí galera! Muito top!
> 
> @alanaraujop @yagovaluchedevs @ramonxm @Brenont @joaoprferreira

Ficou top 🎯 já até reclamou que não ta na melhores práticas rsrs

**Comment by ramonxm** [comment]
Fala @jonataspinto, vai subir mais algo nessa branch ou podemos mergear? Vai falhar o deploy mas acho que não tem muito o que fazer, vamos corrigindo no desenvolvimento.

**Pull request merged**
