### PR TITLE
[feature] Implement Next Seo and more configs

### PR DESCRIPTION
**Pull request by ramonxm**
## Description

Adicionado o next-seo para melhorar indexação dos mecanismo de busca, criado manifest.json e adicionando progressbar para melhoria de ux.

## Screenshots / Videos

https://user-images.githubusercontent.com/38158476/157442978-d519035a-0c5b-4725-8e2b-992b48839962.mov

## Developer Checks

- [X] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [X] Tested on browser device
- [X] Tested on Mobile device

### CODE REVIEW

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.97 | ✅ |
| First Contentful Paint | 1.0 s |  |
| Time to Interactive | 4.2 s |  |
| Speed Index | 1.3 s |  |
| Total Blocking Time | 120 ms |  |
| Largest Contentful Paint | 2.0 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.9 s |  |
| Speed Index | 1.9 s |  |
| Total Blocking Time | 130 ms |  |
| Largest Contentful Paint | 2.1 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by ramonxm** [comment]
@jonataspinto marcando apenas pq não sei se chegou notificação

**Review by jonataspinto — CHANGES_REQUESTED** [review]
Tem que remover os que estão no header não?

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.95 | ✅ |
| First Contentful Paint | 1.2 s |  |
| Time to Interactive | 4.3 s |  |
| Speed Index | 1.7 s |  |
| Total Blocking Time | 280 ms |  |
| Largest Contentful Paint | 1.7 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.92 | ✅ |
| First Contentful Paint | 2.1 s |  |
| Time to Interactive | 6.2 s |  |
| Speed Index | 2.5 s |  |
| Total Blocking Time | 110 ms |  |
| Largest Contentful Paint | 2.1 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Comment by ramonxm** [comment]
> Tem que remover os que estão no head não?

Yeah, esqueci de remover, valeu!

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.85 | ✅ |
| First Contentful Paint | 1.2 s |  |
| Time to Interactive | 4.4 s |  |
| Speed Index | 1.9 s |  |
| Total Blocking Time | 590 ms |  |
| Largest Contentful Paint | 2.0 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 2.0 s |  |
| Time to Interactive | 5.3 s |  |
| Speed Index | 2.4 s |  |
| Total Blocking Time | 100 ms |  |
| Largest Contentful Paint | 2.1 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Review by jonataspinto — APPROVED** [review]

**Comment by jonataspinto** [comment]
LGTM

**Pull request merged**
