### PR TITLE
Feature/footer component

### PR DESCRIPTION
**Pull request by jonataspinto**
## Screenshots 

image

## Developer Checks

- [x] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [x] Tested on browser device
- [x] Tested on Mobile device

### CODE REVIEW

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.48 | ✅ |
| First Contentful Paint | 4.4 s |  |
| Time to Interactive | 5.4 s |  |
| Speed Index | 6.4 s |  |
| Total Blocking Time | 420 ms |  |
| Largest Contentful Paint | 6.7 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.96 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 4.7 s |  |
| Speed Index | 2.1 s |  |
| Total Blocking Time | 90 ms |  |
| Largest Contentful Paint | 1.7 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.62 | ✅ |
| First Contentful Paint | 3.9 s |  |
| Time to Interactive | 4.8 s |  |
| Speed Index | 4.1 s |  |
| Total Blocking Time | 450 ms |  |
| Largest Contentful Paint | 4.8 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.96 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 4.7 s |  |
| Speed Index | 2.1 s |  |
| Total Blocking Time | 110 ms |  |
| Largest Contentful Paint | 1.7 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by ramonxm** [comment]
Atualiza essa branch com o typography

**Comment by ramonxm** [comment]
> Atualiza essa branch com o typography

@jonataspinto

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.51 | ✅ |
| First Contentful Paint | 3.8 s |  |
| Time to Interactive | 5.6 s |  |
| Speed Index | 5.4 s |  |
| Total Blocking Time | 570 ms |  |
| Largest Contentful Paint | 5.5 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.96 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 4.7 s |  |
| Speed Index | 2.1 s |  |
| Total Blocking Time | 100 ms |  |
| Largest Contentful Paint | 1.7 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.59 | ✅ |
| First Contentful Paint | 3.9 s |  |
| Time to Interactive | 4.8 s |  |
| Speed Index | 5.2 s |  |
| Total Blocking Time | 440 ms |  |
| Largest Contentful Paint | 4.8 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.77 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.1 s |  |
| Speed Index | 2.2 s |  |
| Total Blocking Time | 80 ms |  |
| Largest Contentful Paint | 5.2 s |  |
| Cumulative Layout Shift | 0.005 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by jonataspinto** [comment]
> Atualiza essa branch com o typography

feito!

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.66 | ✅ |
| First Contentful Paint | 2.7 s |  |
| Time to Interactive | 5.1 s |  |
| Speed Index | 3.2 s |  |
| Total Blocking Time | 400 ms |  |
| Largest Contentful Paint | 5.6 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.81 | ✅ |
| First Contentful Paint | 1.5 s |  |
| Time to Interactive | 4.2 s |  |
| Speed Index | 1.8 s |  |
| Total Blocking Time | 40 ms |  |
| Largest Contentful Paint | 4.7 s |  |
| Cumulative Layout Shift | 0.005 |  |

    
</details>

**Comment by jonataspinto** [comment]
[Criar componente Footer](https://trello.com/c/rSC5IltN/23-criar-componente-footer)

**Pull request merged**
