### PR TITLE
Fix/set a new max-width to large screen

### PR DESCRIPTION
**Pull request by jonataspinto**
## Description

Adicionoando tamanho máximo igual para cada seção, para melhorar alinhamento.

## Screenshots / Videos

image
image

## Developer Checks

- [x] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [x] Tested on browser device
- [x] Tested on Mobile device

### CODE REVIEW

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.97 | ✅ |
| First Contentful Paint | 1.1 s |  |
| Time to Interactive | 4.4 s |  |
| Speed Index | 2.2 s |  |
| Total Blocking Time | 150 ms |  |
| Largest Contentful Paint | 1.1 s |  |
| Cumulative Layout Shift | 0.056 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.93 | ✅ |
| First Contentful Paint | 1.8 s |  |
| Time to Interactive | 5.4 s |  |
| Speed Index | 2.6 s |  |
| Total Blocking Time | 220 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Review by ramonxm — APPROVED** [review]
LGTM

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.93 | ✅ |
| First Contentful Paint | 1.1 s |  |
| Time to Interactive | 4.4 s |  |
| Speed Index | 2.6 s |  |
| Total Blocking Time | 320 ms |  |
| Largest Contentful Paint | 1.7 s |  |
| Cumulative Layout Shift | 0.056 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.93 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.3 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 200 ms |  |
| Largest Contentful Paint | 2.1 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Pull request merged**
