### PR TITLE
feat: adding github icon

### PR DESCRIPTION
**Pull request by ramonxm**
## Description

Provide a description of what was changed and why it was implemented this way.

## Dev Notes

- If any developer notes are required, list them here. If not, remove the 'Notes' section.

### Steps

1. List all steps in a numbered list

## Screenshots / Videos

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

### CODE REVIEW

**Comment by estartandodevs** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.89 | ✅ |
| First Contentful Paint | 1.3 s |  |
| Time to Interactive | 7.3 s |  |
| Speed Index | 1.6 s |  |
| Total Blocking Time | 320 ms |  |
| Largest Contentful Paint | 1.3 s |  |
| Cumulative Layout Shift | 0.021 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.87 | ✅ |
| First Contentful Paint | 2.3 s |  |
| Time to Interactive | 6.0 s |  |
| Speed Index | 3.1 s |  |
| Total Blocking Time | 150 ms |  |
| Largest Contentful Paint | 2.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by estartandodevs — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? **GitHub runners could be the cause.**
[Try running on Foo instead](https://www.foo.software/docs/lighthouse-check-github-action/examples#running-on-foo-and-saving-results)

**Comment by estartandodevs** [comment]
**Size Change:** 0 B 🆕

**Total Size:** 0 B



<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

**Review by jonataspinto — APPROVED** [review]
LGTM

**Pull request merged**
