### PR TITLE
refactor: add mocks and passing dangerous html

### PR DESCRIPTION
**Pull request by ramonxm**
## Description

Fazendo algumas melhorias 

## Developer Checks

- [X] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [X] Tested on browser device
- [X] Tested on Mobile device

### CODE REVIEW

**Review by jonataspinto — APPROVED** [review]
Boa, só da uma olhada com `lint` e `prettier` antes do merge pq falhou o build 👌🏾

**Comment by ramonxm** [comment]
> Boa, só da uma olhada com `lint` e `prettier` antes do merge pq falhou o build 👌🏾

Meu vscode deu uma bugada aqui e não ta funcionando o lint e o prettier. 

> Boa, só da uma olhada com `lint` e `prettier` antes do merge pq falhou o build 👌🏾

Mal, meu vscode bugou e não consertou automaticamente, vou subir

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.64 | ✅ |
| First Contentful Paint | 3.1 s |  |
| Time to Interactive | 4.7 s |  |
| Speed Index | 3.8 s |  |
| Total Blocking Time | 740 ms |  |
| Largest Contentful Paint | 3.7 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 1.8 s |  |
| Time to Interactive | 5.5 s |  |
| Speed Index | 2.6 s |  |
| Total Blocking Time | 110 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.84 | ✅ |
| First Contentful Paint | 2.4 s |  |
| Time to Interactive | 4.7 s |  |
| Speed Index | 2.6 s |  |
| Total Blocking Time | 350 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.94 | ✅ |
| First Contentful Paint | 1.8 s |  |
| Time to Interactive | 5.2 s |  |
| Speed Index | 2.9 s |  |
| Total Blocking Time | 190 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.044 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by jonataspinto** [comment]
Agora sim!

**Pull request merged**
