### PR TITLE
refact: fixing text

### PR DESCRIPTION
**Pull request by joaoprferreira**
Signed-off-by: João Pedro <joaof082@gmail.com>

## Description

consertando uma palavra que estava errada no perfil do aluno.

## Screenshots / Videos

image

image

Add any relevant screenshots or videos. Any video should be added to the Jira ticket and linked here.

## Developer Checks

- [x] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [x] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [x] Tested on browser device
- [x] Tested on Mobile device

### CODE REVIEW

**Review by Brenont — APPROVED** [review]

**Review by ramonxm — APPROVED** [review]

**Comment by Brenont** [comment]
LGTM 👍

**Comment by jonataspinto** [comment]
Gooooood

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.74 | ✅ |
| First Contentful Paint | 3.0 s |  |
| Time to Interactive | 4.6 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 490 ms |  |
| Largest Contentful Paint | 3.6 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.92 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 5.1 s |  |
| Speed Index | 3.0 s |  |
| Total Blocking Time | 290 ms |  |
| Largest Contentful Paint | 1.7 s |  |
| Cumulative Layout Shift | 0.056 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Pull request merged**
