### PR TITLE
[feature] implement lint staged

### PR DESCRIPTION
**Pull request by ramonxm**
## Description

Vendo que muitos PR's demostram errors de builds por eslint e etc, adicionei um hook para commit pelo husky e configs de commit semantico, além do lint staged.

## Developer Checks

- [X] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [X] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [X] Tested on browser device
- [X] Tested on Mobile device

### CODE REVIEW

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.69 | ✅ |
| First Contentful Paint | 1.8 s |  |
| Time to Interactive | 7.9 s |  |
| Speed Index | 3.2 s |  |
| Total Blocking Time | 1,060 ms |  |
| Largest Contentful Paint | 1.8 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.79 | ✅ |
| First Contentful Paint | 2.7 s |  |
| Time to Interactive | 7.2 s |  |
| Speed Index | 4.3 s |  |
| Total Blocking Time | 160 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Review by jonataspinto — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by jonataspinto** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.71 | ✅ |
| First Contentful Paint | 1.7 s |  |
| Time to Interactive | 7.6 s |  |
| Speed Index | 3.4 s |  |
| Total Blocking Time | 770 ms |  |
| Largest Contentful Paint | 2.5 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.81 | ✅ |
| First Contentful Paint | 2.6 s |  |
| Time to Interactive | 7.1 s |  |
| Speed Index | 3.9 s |  |
| Total Blocking Time | 160 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Comment by ramonxm** [comment]
@jonataspinto , baixa sua branch dps e dá `git commit`, se estourar algum erro me fala?

**Comment by estartandodevs** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.39 | ✅ |
| First Contentful Paint | 2.7 s |  |
| Time to Interactive | 10.1 s |  |
| Speed Index | 6.3 s |  |
| Total Blocking Time | 2,090 ms |  |
| Largest Contentful Paint | 4.3 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.8 | ✅ |
| First Contentful Paint | 2.6 s |  |
| Time to Interactive | 7.2 s |  |
| Speed Index | 4.0 s |  |
| Total Blocking Time | 200 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by estartandodevs — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by estartandodevs** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.3 | ✅ |
| First Contentful Paint | 2.7 s |  |
| Time to Interactive | 10.6 s |  |
| Speed Index | 6.0 s |  |
| Total Blocking Time | 2,410 ms |  |
| Largest Contentful Paint | 7.1 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.81 | ✅ |
| First Contentful Paint | 2.6 s |  |
| Time to Interactive | 7.0 s |  |
| Speed Index | 3.9 s |  |
| Total Blocking Time | 160 ms |  |
| Largest Contentful Paint | 3.2 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by estartandodevs — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Review by jonataspinto — APPROVED** [review]
Boa ramon!

LGTM 🚀

**Comment by estartandodevs** [comment]
<details>
    <summary>Lighthouse result for https://www.estartandodevs.com.br/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.81 | ✅ |
| First Contentful Paint | 1.1 s |  |
| Time to Interactive | 7.4 s |  |
| Speed Index | 2.5 s |  |
| Total Blocking Time | 310 ms |  |
| Largest Contentful Paint | 3.4 s |  |
| Cumulative Layout Shift | 0 |  |

    
</details>
<details>
    <summary>Lighthouse result for http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/</summary>
    

  | Metric | Score |  |
  | --- | --- | --- |
  | Performance | 0.87 | ✅ |
| First Contentful Paint | 2.3 s |  |
| Time to Interactive | 6.7 s |  |
| Speed Index | 2.9 s |  |
| Total Blocking Time | 130 ms |  |
| Largest Contentful Paint | 2.9 s |  |
| Cumulative Layout Shift | 0.001 |  |

    
</details>

**Review by estartandodevs — COMMENTED** [review]
| Device | URL |
|--|--|
| desktop | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

     
| Device | URL |
|--|--|
| mobile | http://estartandodevs-site.s3-website-sa-east-1.amazonaws.com/ |

Not what you expected? Are your scores flaky? [Run Lighthouse on Foo](https://www.foo.software/lighthouse)
If scores continue to be inconsistent consider [running all audits on Foo](https://github.com/foo-software/lighthouse-check-action#usage-foos-automated-lighthouse-check-api)

**Comment by ramonxm** [comment]
Alias to run commit with lint:  git config alias.commitlint '!yarn commit'

**Comment by ramonxm** [comment]
> > Alias to run commit with lint:
> > `git config alias.commitlint '!yarn commit'`
> 
> Tem que ter a exclamação na frente?

Sim, quando é algum custom command do próprio repo você coloca !

**Pull request merged**
