### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jonataspinto**
## Description
- Atualização para next13 

## Developer Checks

- [ ] PR title & commits adhere to [Conventional Commit Specification](https://www.conventionalcommits.org/en/v1.0.0/)
- [ ] PR is targeting correct branch, is up-to-date, & no merge conflicts
- [ ] Tested on browser device
- [ ] Tested on Mobile device

### CODE REVIEW

**Review by jonataspinto — COMMENTED** [review]
Beautiful 👨🏾‍🎨

**Comment by ramonxm** [comment]
Why not update next to 14?

**Comment by jonataspinto** [comment]
> Why not update next to 14?

I don't know. you are the father of the child

**Comment by jonataspinto** [comment]
at some point dependbot will do this

**Comment by ramonxm** [comment]
It is necessary to migrate to the new app dir standard, this will require major refactoring

**Pull request merged**
